### ISSUE TITLE
hello-worldブランチを作る

### ISSUE THREAD

**Issue by KoinoEngineering** [Hitomi-Ozeki/nuxt-practice-todo#2]
1. masterの最新からhello-worldブランチを作る
2. hello-worldブランチをチェックアウトする

- 実際にたたいたコマンドのテキスト
- 画面上どうなったのかキャプチャ
をコメントに記載する

**Comment by KoinoEngineering** [comment]
@Hitomi-Ozeki 
たとえばファイルリストを出してディレクトリを移動するだけならこんな感じ

これの`ブランチ作成してチェックアウトする版`をコメントに入れる
```
$ ls
$ cd app
```
![image](https://user-images.githubusercontent.com/40349284/152676272-6d980258-48e1-4122-8de1-abaa09bd2ab1.png)

**Comment by Hitomi-Ozeki** [comment]
<img width="1440" alt="スクリーンショット 2022-02-06 19 25 47" src="https://user-images.githubusercontent.com/98302078/152676629-41131686-da3e-4a3f-8f08-0d26bdf17de3.png">
とりあえず今どんなブランチがあるのか確認してみた。マスターだけだった

**Comment by Hitomi-Ozeki** [comment]
<img width="1440" alt="スクリーンショット 2022-02-06 19 27 55" src="https://user-images.githubusercontent.com/98302078/152676689-e287f156-438d-49c2-a8d8-46f01b79b3bc.png">
hello-wordブランチができた

**Comment by Hitomi-Ozeki** [comment]
<img width="1440" alt="スクリーンショット 2022-02-06 19 31 33" src="https://user-images.githubusercontent.com/98302078/152676775-799b670b-4597-41bb-9dae-5cb6c559dec4.png">
branch切り替えた。色が変わってるから今helloーwordにいることも確認できた。

**Comment by Hitomi-Ozeki** [comment]
$ git branch hello-word
$ git checkout hello-word
<img width="523" alt="スクリーンショット 2022-02-06 19 49 42" src="https://user-images.githubusercontent.com/98302078/152677384-e8294176-5cb3-43cf-96bd-55fc072ea69e.png">

**Comment by Hitomi-Ozeki** [comment]
```
$ git branch hello-word
$ git checkout hello-word
```
<img width="523" alt="スクリーンショット 2022-02-06 19 49 42" src="https://user-images.githubusercontent.com/98302078/152677858-d246c25e-f471-4957-b1fc-2f6c2b796173.png">

**Comment by KoinoEngineering** [comment]
@Hitomi-Ozeki 
LGTM
