### ISSUE TITLE
HelloWorld!

### ISSUE THREAD

**Issue by KoinoEngineering** [Hitomi-Ozeki/nuxt-practice-todo#3]
1. 任意のパスで`HelloWorld!`が表示できる画面を作る
2. githubにpushする
3. PRを作成する
4. PRがマージされるまで対応する

**Comment by Hitomi-Ozeki** [comment]
```
$ yarn
$ yarn dev
```

**Comment by Hitomi-Ozeki** [comment]
<img width="416" alt="スクリーンショット 2022-02-10 18 38 23" src="https://user-images.githubusercontent.com/98302078/153381273-b784b0a3-d059-48e5-95c2-9b0b2c9a0462.png">

**Comment by Hitomi-Ozeki** [comment]
<img width="404" alt="スクリーンショット 2022-02-10 19 06 37" src="https://user-images.githubusercontent.com/98302078/153385073-46cddfed-cba9-46bd-ae62-a475c3902d87.png">
